from datetime import datetime
from datetime import timedelta

TODAY = datetime.now()
WORK_TIME = timedelta(minutes=30)
BREAK_TIME = timedelta(minutes=15)

ADD_WORK_TIME = TODAY+WORK_TIME
ADD_BREAK_TIME = TODAY+BREAK_TIME


DATE = "(W)DATE"
START_TIME = "(W)START TIME"
WORK_DURATION = "(W)WORK DURATION"
END_TIME = "(W)END TIME"

WORK_HEADLINES = [DATE, START_TIME, WORK_DURATION, END_TIME]

DATE = "(B)DATE"
START_TIME = "(B)START TIME"
BREAK_DURATION = "(B)BREAK DURATION"
END_TIME = "(B)END TIME"

BREAK_HEADLINES = [DATE, START_TIME, BREAK_DURATION, END_TIME]
